### PR TITLE
Added support for multiple scoring functions

### PR DESCRIPTION
**Pull request by kevloui**

### CODE REVIEW

**Review by brianjimenez — CHANGES_REQUESTED** [review]
Please, could you use uppercase for DFIRE and DLIGAND2 scoring methods? It's not following the standard for class/objects names, but as an acronym should be better in uppercase and it's the name given by the original authors.
One of the unit tests is failing (`cargo test`) with the following message:

```
---- scoring::tests::test_read_potentials stdout ----
thread 'scoring::tests::test_read_potentials' panicked at 'Unable to open the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/scoring.rs:231:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kevloui** [comment]
The error has been fixed with the new code, please let me know if it's changed for you? Also changed method naming to caps.

**Comment by brianjimenez** [comment]
> The error has been fixed with the new code, please let me know if it's changed for you? Also changed method naming to caps.

Nice, tests are working nicely, but a couple of more small issues still to fix:

1. In file `bin/lightdock-rust.rs` line 120, error message should also indicate the method
2. From the main `README.md`, if you try 1ppe for example, code panics with the following message:

```
[~/lightdock-rust/example/1ppe]: time ../../target/release/lightdock-rust setup_1ppe.json initial_positions_0.dat 100 dfire
Reading starting positions from "initial_positions_0.dat"
Reading receptor input structure: lightdock_1ppe_e.pdb
Reading ligand input structure: lightdock_1ppe_i.pdb
Loading DFIRE scoring function
thread '<unnamed>' panicked at 'Unable to open the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/scoring.rs:230:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/bin/lightdock-rust.rs:85:5
```
which is basically not finding the DFIRE parameters file.

**Comment by kevloui** [comment]
I think I know why this happens. Do you have all of the binaries in your src folder?

**Comment by brianjimenez** [comment]
> I think I know why this happens. Do you have all of the binaries in your src folder?

Binaries are in the `target/release` folder. Maybe it would be a better idea to have all the parameters files in a separate `data` folder which both the tests and binaries would find. Does it sound good?

**Comment by kevloui** [comment]
Have a go at this one, if it still doesn't work for you, let me know where to move the data.

**Pull request merged**
